#!/usr/bin/env sh

print_usage() {
  printf "Usage: script -u (unrevoke) <clientname> OR script -r (revoke) <clientname>"
}

restart() {
    touch /etc/wireguard/restart
    sleep 1
    rm /etc/wireguard/restart
}

revoke() {
    NAME=$1
    if [ -e "/etc/wireguard/clients/$NAME.pub" ]; then
        mv /etc/wireguard/clients/"$NAME".pub /etc/wireguard/clients/"$NAME"-REV.pub
        restart
    else
    if [ "$CLIENTCONTROL_NO_LOGS" -eq 0 ]
    then
            printf '%s has not been created yet' "$NAME"
        fi
    exit 1
    fi
}

unrevoke() {
    NAME=$1
    if [ -e "/etc/wireguard/clients/$NAME-REV.pub" ]; then
        mv /etc/wireguard/clients/"$NAME"-REV.pub /etc/wireguard/clients/"$NAME".pub
        restart
    elif [ -e "/etc/wireguard/clients/$NAME.pub" ]; then
        if [ "$CLIENTCONTROL_NO_LOGS" -eq 0 ]
    then
        printf '%s has not been revoked yet' "$NAME"
    fi
    exit 1
    else
        if [ "$CLIENTCONTROL_NO_LOGS" -eq 0 ]
    then
        printf '%s has not been created yet' "$NAME"
        fi
    exit 1
    fi
}

while getopts 'u:r:' flag; do
  case "${flag}" in
    u) unrevoke "${OPTARG}" ;;
    r) revoke "${OPTARG}" ;;
    *) print_usage
       exit 1 ;;
  esac
done
